### ISSUE TITLE
Getting mean 0 and nan values

### ISSUE THREAD

**Issue by scienception** [sriramlab/FAME#5]
What does this mean:0 mean? and I'm obtaining quite a lot of nan values :/
Also, I'm using phenotypes that are already covariate corrected is that fine?

How I ran it:
```
target=${DIR}/CNV_status_anno/region.DEL.CNV.tsv
gen=${DIR}/BED_files/region.DEL
phen=${DIR}/pheno/region.DEL.PHENO.tsv
annot=${DIR}/variant_proximity_anno/region.anno.txt

${FAME_DIR}/GENIE_GxG -g $gen -p $phen  -annot $annot -tp $target -gxgbin 1 -snp -1  -k 10 -jn 10  -o region.results.txt
```
And what I got:

```
-g
-p
-annot
-tp
-gxgbin
-snp
-k
-jn
-o
#SNP in bim file 77228
570 SNPs in 0-th bin
 Number of selected SNPs w.r.t  annot file : 570
76658 SNPs in 1-th bin
 Number of selected SNPs w.r.t  annot file : 76658
Number of SNPs per block : 7722
325300
Number of Indvs :325300
y_sum is31.8754
selected snp index: -1
selected snp is in 0 jackknife block
selected snp is -1 th snp of block
No Covariate File Specified
region.DEL.bed
reading genotype matrix :
reading 0 block
In read_bed2: about to read: 7722number of snps
bin_index: 0num_snps: 0
bin_index: 1num_snps: 7722
mean :0
mean :0
mean :0
mean :0
mean :0
mean :0
mean :0
mean :0
mean :0
mean :0
mean :0
mean :0
mean :0
mean :0
mean :0
mean :0
mean :0
.
.
.
size of the bins :
bin 0 : 570
bin 1 : 76658
bin 2 : 76658
Xl3.09313e+10        -nan        -nan      325300
       -nan        -nan        -nan      325300
       -nan        -nan        -nan        -nan
     325300      325300        -nan      325300
Yl3.17194e+07
       -nan
       -nan
     301907
sigms
 nan
-nan
-nan
 nan
herit
 nan
-nan
-nan
 nan
d : nan
 nan -nan -nan  nan
-nan -nan -nan -nan
-nan -nan -nan -nan
 nan -nan -nan  nan
-nan -nan -nan -nan
-nan -nan -nan -nan
-nan -nan -nan -nan
-nan -nan -nan -nan
se
-nan
-nan
-nan
-nan
sigma^2_0: nan se: -nan
sigma^2_1: -nan se: -nan
sigma^2_2: -nan se: -nan
sigma^2_3: nan se: -nan

```

Not sure why everything is giving weird null values. Or is it just there is no epistasis detected?

**Comment by scienception** [comment]
Also, can the additive effect of the target be added separately? or where is it placed?

**Comment by scienception** [comment]
in your plink files, which ones are the major and the minor alleles?

**Comment by scienception** [comment]
Could you provide an example with covariates? I added the -c flag (I had to look for it since it wasn't in the documentation nor the examples). But it is not reading the file:
```
Read in 0 Covariates..
Total number of fixed effects: 0
```

**Comment by scienception** [comment]
Any chance you could answer these questions soonish? I would appreciate it! :)

**Comment by FBoyang** [comment]
Hi, thanks for your interest!

This could happen for various reasons. 
1. The input contains NaN/ missing values/ column with a constant value. Please ensure that proper standard QC has been done on the genotype matrix.
2. Upon checking your log, it seems that Xl_1 = 3.09313e+10 can be too large. Can you make sure that the target variable was standardized before the estimation?
3. Please make sure target y has been properly standardized. 

Q: can the additive effect of the target be added separately?
A: You can simply put the target variable to the set of covariates 

Q: in your plink files, which ones are the major and the minor alleles?
A: We follow the same encoding protocol as plink. 

Q: Could you provide an example with covariates? I added the -c flag
A: Can you check if the covariate is space-separated with column name as the first row, FID and IID as the first two columns?

**Comment by scienception** [comment]
This is what I used for QC (in 3 consecutive steps):

1) --keep non_related_white_british.txt --geno 0.01 --maf 0.01 --hwe 1e-7
2) --extract (the GWAS significant variants)
3) --indep-pairwise 500 1 0.1

The target (C_t) is simply a set of 0s and 1s (binary). Do I have to standardize this?

**Comment by scienception** [comment]
Also, what exactly does this mean?

> selected snp index: -1
> selected snp is in 0 jackknife block
> selected snp is -1 th snp of block

 
Does this mean the target is by default I added to the equation? Or the target is not in the equation at all (apart from the interaction term)?
So is it this:
`G1+G2+C_t*G2+ϵ `
Or this:
`G1+G2+C_t+C_t*G2+ϵ `

Thanks again!

**Comment by scienception** [comment]
Last question. Do you 
1) first regress out the covariates (age, sex, PCs, carrier status) from phenotype and then inverse rank normalize the residuals and provide this as 'y' , or...
2) inverse rank normalize the raw phenotype give this as 'y' and then provide the covariates as a separate file?

**Comment by FBoyang** [comment]
1. The target (C_t) is simply a set of 0s and 1s (binary). Do I have to standardize this:
Yes, it is recommended to standardize it, even if it is 0s and 1s.

2. QC step: 
It is great that you took care of the MAF. However, since you are extracting the GWAS significant loci as background, it is suggested that at least the GWAS and FAME are run on two independent splits to avoid potential selection bias.

3. selected snp index: -1 : This is to extend the vanilla FAME software, which requires the target SNP to be presented within the input with a certain index. Here, index = -1 means the target SNP isn't present in the input data. The corresponding equation is: `G1+G2+C_t*G2+ϵ`, meaning that if you want to include C_t's main effect, you can put it as covariates. 

4. Normalization step: It is a good question. We, by default, use 2 (first do ivrt). If the raw phenotype distribution significantly deviates from the normal distribution, then using 1 may cause certain inflation. 

I hope these answer your questions. If the issue remains, I am more than happy to communicate with you over email (via fbyang1995@gmail.com) if any part of the data can be shared.
